//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokemon_and_Friends_Upgrader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WebhookURL {
            get {
                return ((string)(this["WebhookURL"]));
            }
            set {
                this["WebhookURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Language {
            get {
                return ((int)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string RunAwayMin {
            get {
                return ((string)(this["RunAwayMin"]));
            }
            set {
                this["RunAwayMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string RunAwayMax {
            get {
                return ((string)(this["RunAwayMax"]));
            }
            set {
                this["RunAwayMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string FirstPokemonNr {
            get {
                return ((string)(this["FirstPokemonNr"]));
            }
            set {
                this["FirstPokemonNr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("898")]
        public string LastPokemonNr {
            get {
                return ((string)(this["LastPokemonNr"]));
            }
            set {
                this["LastPokemonNr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string ShinyPercentage {
            get {
                return ((string)(this["ShinyPercentage"]));
            }
            set {
                this["ShinyPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("898")]
        public string MaxAmountOfPokemon {
            get {
                return ((string)(this["MaxAmountOfPokemon"]));
            }
            set {
                this["MaxAmountOfPokemon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300000")]
        public string SpawnTimer {
            get {
                return ((string)(this["SpawnTimer"]));
            }
            set {
                this["SpawnTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180000")]
        public string RunTimer {
            get {
                return ((string)(this["RunTimer"]));
            }
            set {
                this["RunTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public string GreatballTimer {
            get {
                return ((string)(this["GreatballTimer"]));
            }
            set {
                this["GreatballTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public string UltraballTimer {
            get {
                return ((string)(this["UltraballTimer"]));
            }
            set {
                this["UltraballTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LoadingScreen {
            get {
                return ((int)(this["LoadingScreen"]));
            }
            set {
                this["LoadingScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SpawnMusic {
            get {
                return ((int)(this["SpawnMusic"]));
            }
            set {
                this["SpawnMusic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BreakoutMessage {
            get {
                return ((int)(this["BreakoutMessage"]));
            }
            set {
                this["BreakoutMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Discord {
            get {
                return ((int)(this["Discord"]));
            }
            set {
                this["Discord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PokemonBot")]
        public string WebhookUser {
            get {
                return ((string)(this["WebhookUser"]));
            }
            set {
                this["WebhookUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public string CatchRate {
            get {
                return ((string)(this["CatchRate"]));
            }
            set {
                this["CatchRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Gift {
            get {
                return ((int)(this["Gift"]));
            }
            set {
                this["Gift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Masterball {
            get {
                return ((int)(this["Masterball"]));
            }
            set {
                this["Masterball"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("files\\LoadingScreen.png")]
        public string LoadingScreenPath {
            get {
                return ((string)(this["LoadingScreenPath"]));
            }
            set {
                this["LoadingScreenPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("files\\shinyblue.png")]
        public string ShinyScreenPath {
            get {
                return ((string)(this["ShinyScreenPath"]));
            }
            set {
                this["ShinyScreenPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Challenger Approaches.mp3")]
        public string LoadingSoundPath {
            get {
                return ((string)(this["LoadingSoundPath"]));
            }
            set {
                this["LoadingSoundPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("chrizzz_1508")]
        public string StreamerName {
            get {
                return ((string)(this["StreamerName"]));
            }
            set {
                this["StreamerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseSummon {
            get {
                return ((int)(this["UseSummon"]));
            }
            set {
                this["UseSummon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MyPokemonWebhook {
            get {
                return ((string)(this["MyPokemonWebhook"]));
            }
            set {
                this["MyPokemonWebhook"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PokemonBot")]
        public string MyPokemonUser {
            get {
                return ((string)(this["MyPokemonUser"]));
            }
            set {
                this["MyPokemonUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UsePriorityThrow {
            get {
                return ((int)(this["UsePriorityThrow"]));
            }
            set {
                this["UsePriorityThrow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseBonusTime {
            get {
                return ((int)(this["UseBonusTime"]));
            }
            set {
                this["UseBonusTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300000")]
        public string BonusTime {
            get {
                return ((string)(this["BonusTime"]));
            }
            set {
                this["BonusTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseThrowOvertime {
            get {
                return ((int)(this["UseThrowOvertime"]));
            }
            set {
                this["UseThrowOvertime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseThrowMessage {
            get {
                return ((int)(this["UseThrowMessage"]));
            }
            set {
                this["UseThrowMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int UseSeperateWebhook {
            get {
                return ((int)(this["UseSeperateWebhook"]));
            }
            set {
                this["UseSeperateWebhook"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseRefundMessage {
            get {
                return ((int)(this["UseRefundMessage"]));
            }
            set {
                this["UseRefundMessage"] = value;
            }
        }
    }
}
