//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokemon_and_Friends_Upgrader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SAMMI {
            get {
                return ((string)(this["SAMMI"]));
            }
            set {
                this["SAMMI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Language {
            get {
                return ((int)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NonAffiliate {
            get {
                return ((int)(this["NonAffiliate"]));
            }
            set {
                this["NonAffiliate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public string AudioTreshhold {
            get {
                return ((string)(this["AudioTreshhold"]));
            }
            set {
                this["AudioTreshhold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4444")]
        public string OBSWSPort {
            get {
                return ((string)(this["OBSWSPort"]));
            }
            set {
                this["OBSWSPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OBSWSPW {
            get {
                return ((string)(this["OBSWSPW"]));
            }
            set {
                this["OBSWSPW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Gifs {
            get {
                return ((int)(this["Gifs"]));
            }
            set {
                this["Gifs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public string SpawnTimer {
            get {
                return ((string)(this["SpawnTimer"]));
            }
            set {
                this["SpawnTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string SpawnChance {
            get {
                return ((string)(this["SpawnChance"]));
            }
            set {
                this["SpawnChance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SpawnMusic {
            get {
                return ((int)(this["SpawnMusic"]));
            }
            set {
                this["SpawnMusic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LoadingScreen {
            get {
                return ((int)(this["LoadingScreen"]));
            }
            set {
                this["LoadingScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int LoadingAnimation {
            get {
                return ((int)(this["LoadingAnimation"]));
            }
            set {
                this["LoadingAnimation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string CatchValuePokeball {
            get {
                return ((string)(this["CatchValuePokeball"]));
            }
            set {
                this["CatchValuePokeball"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string CatchValueGreatball {
            get {
                return ((string)(this["CatchValueGreatball"]));
            }
            set {
                this["CatchValueGreatball"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public string CatchValueUltraball {
            get {
                return ((string)(this["CatchValueUltraball"]));
            }
            set {
                this["CatchValueUltraball"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string CatchMinIncrease {
            get {
                return ((string)(this["CatchMinIncrease"]));
            }
            set {
                this["CatchMinIncrease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string CatchMaxIncrease {
            get {
                return ((string)(this["CatchMaxIncrease"]));
            }
            set {
                this["CatchMaxIncrease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseBonustime {
            get {
                return ((int)(this["UseBonustime"]));
            }
            set {
                this["UseBonustime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string BonusTimeMinUsers {
            get {
                return ((string)(this["BonusTimeMinUsers"]));
            }
            set {
                this["BonusTimeMinUsers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public string BonusTimeSpawnTimer {
            get {
                return ((string)(this["BonusTimeSpawnTimer"]));
            }
            set {
                this["BonusTimeSpawnTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string RunAwayMinIncrease {
            get {
                return ((string)(this["RunAwayMinIncrease"]));
            }
            set {
                this["RunAwayMinIncrease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string RunAwayMaxIncrease {
            get {
                return ((string)(this["RunAwayMaxIncrease"]));
            }
            set {
                this["RunAwayMaxIncrease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public string RunTimer {
            get {
                return ((string)(this["RunTimer"]));
            }
            set {
                this["RunTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseDiscord {
            get {
                return ((int)(this["UseDiscord"]));
            }
            set {
                this["UseDiscord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int UseSepareteWebhook {
            get {
                return ((int)(this["UseSepareteWebhook"]));
            }
            set {
                this["UseSepareteWebhook"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WebhookURLCatch {
            get {
                return ((string)(this["WebhookURLCatch"]));
            }
            set {
                this["WebhookURLCatch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WebhookURLMYP {
            get {
                return ((string)(this["WebhookURLMYP"]));
            }
            set {
                this["WebhookURLMYP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int UseBreakoutMessage {
            get {
                return ((int)(this["UseBreakoutMessage"]));
            }
            set {
                this["UseBreakoutMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseRefundMessage {
            get {
                return ((int)(this["UseRefundMessage"]));
            }
            set {
                this["UseRefundMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseRunMessage {
            get {
                return ((int)(this["UseRunMessage"]));
            }
            set {
                this["UseRunMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("files\\loadingscreens\\WildPokemonEnglish.png")]
        public string LoadingScreenPath {
            get {
                return ((string)(this["LoadingScreenPath"]));
            }
            set {
                this["LoadingScreenPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("files\\shinybackgrounds\\shinygold.png")]
        public string ShinyScreenPath {
            get {
                return ((string)(this["ShinyScreenPath"]));
            }
            set {
                this["ShinyScreenPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pokemon Battle.mp3")]
        public string LoadingSoundPath {
            get {
                return ((string)(this["LoadingSoundPath"]));
            }
            set {
                this["LoadingSoundPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pokeball")]
        public string NamePokeball {
            get {
                return ((string)(this["NamePokeball"]));
            }
            set {
                this["NamePokeball"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Greatball")]
        public string NameGreatball {
            get {
                return ((string)(this["NameGreatball"]));
            }
            set {
                this["NameGreatball"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseGreatball {
            get {
                return ((int)(this["UseGreatball"]));
            }
            set {
                this["UseGreatball"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ultraball")]
        public string NameUltraball {
            get {
                return ((string)(this["NameUltraball"]));
            }
            set {
                this["NameUltraball"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseUltraball {
            get {
                return ((int)(this["UseUltraball"]));
            }
            set {
                this["UseUltraball"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Masterball")]
        public string NameMasterball {
            get {
                return ((string)(this["NameMasterball"]));
            }
            set {
                this["NameMasterball"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseMasterball {
            get {
                return ((int)(this["UseMasterball"]));
            }
            set {
                this["UseMasterball"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mystery Pokemon")]
        public string NameMysteryPokemon {
            get {
                return ((string)(this["NameMysteryPokemon"]));
            }
            set {
                this["NameMysteryPokemon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseMysteryPokemon {
            get {
                return ((int)(this["UseMysteryPokemon"]));
            }
            set {
                this["UseMysteryPokemon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mystery Shiny")]
        public string NameMysteryShiny {
            get {
                return ((string)(this["NameMysteryShiny"]));
            }
            set {
                this["NameMysteryShiny"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseMysteryShiny {
            get {
                return ((int)(this["UseMysteryShiny"]));
            }
            set {
                this["UseMysteryShiny"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Summon Pokemon")]
        public string NameSummon {
            get {
                return ((string)(this["NameSummon"]));
            }
            set {
                this["NameSummon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseSummon {
            get {
                return ((int)(this["UseSummon"]));
            }
            set {
                this["UseSummon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Give a Gift")]
        public string NameGift {
            get {
                return ((string)(this["NameGift"]));
            }
            set {
                this["NameGift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseGift {
            get {
                return ((int)(this["UseGift"]));
            }
            set {
                this["UseGift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int UseSpawnChance {
            get {
                return ((int)(this["UseSpawnChance"]));
            }
            set {
                this["UseSpawnChance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public string BonusTimeDuration {
            get {
                return ((string)(this["BonusTimeDuration"]));
            }
            set {
                this["BonusTimeDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string ShinyChance {
            get {
                return ((string)(this["ShinyChance"]));
            }
            set {
                this["ShinyChance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string PricePokeball {
            get {
                return ((string)(this["PricePokeball"]));
            }
            set {
                this["PricePokeball"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public string PriceGreatball {
            get {
                return ((string)(this["PriceGreatball"]));
            }
            set {
                this["PriceGreatball"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string PriceUltraball {
            get {
                return ((string)(this["PriceUltraball"]));
            }
            set {
                this["PriceUltraball"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25000")]
        public string PriceMasterball {
            get {
                return ((string)(this["PriceMasterball"]));
            }
            set {
                this["PriceMasterball"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public string PriceSummon {
            get {
                return ((string)(this["PriceSummon"]));
            }
            set {
                this["PriceSummon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string PriceMysteryPokemon {
            get {
                return ((string)(this["PriceMysteryPokemon"]));
            }
            set {
                this["PriceMysteryPokemon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public string PriceMysteryShiny {
            get {
                return ((string)(this["PriceMysteryShiny"]));
            }
            set {
                this["PriceMysteryShiny"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public string PriceGift {
            get {
                return ((string)(this["PriceGift"]));
            }
            set {
                this["PriceGift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AnnounceRarePokemons {
            get {
                return ((int)(this["AnnounceRarePokemons"]));
            }
            set {
                this["AnnounceRarePokemons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseAnimatedTrainers {
            get {
                return ((int)(this["UseAnimatedTrainers"]));
            }
            set {
                this["UseAnimatedTrainers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BroadcasterName {
            get {
                return ((string)(this["BroadcasterName"]));
            }
            set {
                this["BroadcasterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseGen1 {
            get {
                return ((int)(this["UseGen1"]));
            }
            set {
                this["UseGen1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseGen2 {
            get {
                return ((int)(this["UseGen2"]));
            }
            set {
                this["UseGen2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseGen3 {
            get {
                return ((int)(this["UseGen3"]));
            }
            set {
                this["UseGen3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseGen4 {
            get {
                return ((int)(this["UseGen4"]));
            }
            set {
                this["UseGen4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseGen5 {
            get {
                return ((int)(this["UseGen5"]));
            }
            set {
                this["UseGen5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseGen6 {
            get {
                return ((int)(this["UseGen6"]));
            }
            set {
                this["UseGen6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseGen7 {
            get {
                return ((int)(this["UseGen7"]));
            }
            set {
                this["UseGen7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseGen8 {
            get {
                return ((int)(this["UseGen8"]));
            }
            set {
                this["UseGen8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseRegionals {
            get {
                return ((int)(this["UseRegionals"]));
            }
            set {
                this["UseRegionals"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseCustomPokemon {
            get {
                return ((int)(this["UseCustomPokemon"]));
            }
            set {
                this["UseCustomPokemon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string QueueTime {
            get {
                return ((string)(this["QueueTime"]));
            }
            set {
                this["QueueTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UseMega {
            get {
                return ((int)(this["UseMega"]));
            }
            set {
                this["UseMega"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OBSPath {
            get {
                return ((string)(this["OBSPath"]));
            }
            set {
                this["OBSPath"] = value;
            }
        }
    }
}
